class Insertar < ActiveRecord::Migration
  def self.up
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Irineo','Vargas',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Paulino','Andia',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Estanislao','Bofill',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('German','Sains',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Alberto','Del Vecchio',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Magno','Huanto',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Philipus','Alek',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Marcelo','Bazan',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Sergio','Gamberoni',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Jesus','Moreno',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Wilson','Sejas',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Fernando','Rojas','Silva','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Federico','Torrico',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Hugo','Saravia',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Txema','Martinez','De La Fuente','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Pastor','Pacsi',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Cirilo','Aceituno',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Wilson','Selinas',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Antonio','Alcocer',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Antonio','Chocarro',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Armando','Sejas',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Edwin','Quispe',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Cleto','Hinojosa',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Valerio','Modena',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Fernando','Gallo',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Francisco','Dardichon',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Jesus E.','Osorno','Gil','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Jose','Senteno',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Marco','Verberckt',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Enrrique','Zabala',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Jaques','Delor',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Jose','Gallo',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Evar','Fernandez',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Elio','Di Lenarda',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Francisco','Gutierrez',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Tomas','Mamani',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Miguel Angel','Aymar',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Javier','Ulunque',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Juan','Guzman',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Crispin','Borda',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Massimo','Fratus',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Alejo','Gerling',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Paolo','Archetti',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Carlos E.','Curiel','H.','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Simon','Leaño','Duchen','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Roberto','Caceres',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Amado','Camacho',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Sergio','Montes',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Lazaro','Torrico',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Felix','Parra',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Marcial','Sanchez',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Virgilio','Anturiano',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Enrrique','Bustamante',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Lucio','Arnez',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Antonio','Gil','Aguilera','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Rodolfo','Benavente',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Victor','Benavente',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Joaquin','Herbas',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Walter','Rocha',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Rodolfo','Ramirez',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Francisco Pablo','Ross','Gallo','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Tomas','Flores',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Manfredo','Rauh',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Jhonny','Villarroel',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Reynaldo','Acometa',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Gregorio','Di Marchi',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Mauro','Palamini',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Misioneras De Jesus','V y Victima',' ','10/10/2010');"
    execute "insert into pastors(name,primary_last_name,second_last_name,date_of_birth) values('Esperandio','Ravasio',' ','10/10/2010');"
  end

  def self.down
    execute "truncate table pastors"   
  end
end
